const Cupons = require('../../domain/entities/cupons.entity');
const { NotFoundError } = require('../../domain/errors');

class CuponsService {
    constructor(cuponsRepository) { // ¡Depende de la interfaz!
        this.cuponsRepository = cuponsRepository;
    }
    
    async getAllCupons() {
        return this.cuponsRepository.getAll();
    }

    async getCuponsById(id) {
        const cupons = await this.cuponsRepository.getById(id);
        if (!cupons) {
            throw new NotFoundError(`Product with id ${id} not found`);
        }
        return cupons;
    }

    async createCupons(cuponsData) {
        // Aquí podría haber lógica de negocio y validaciones
        const cuponEntity = new Cupons(
            null, // ID is null because it will be generated by the database
            cuponsData.description,
            cuponsData.price,
            cuponsData.category,
        );
        return this.cuponsRepository.create(cuponEntity);
    }

    async updateCupons(id, cuponsData) {
        const cupon = await this.cuponsRepository.getById(id);
        if (!cupon) {
            throw new NotFoundError(`Product with id ${id} not found`);
        }
        const updatedCupon = new Cupons(
            id,
            cuponsData.description,
            cuponsData.price,
            cuponsData.category
        );
        return this.cuponsRepository.update(id, updatedCupon);
    }

    async deleteCupons(id) {
        const cupons = await this.cuponsRepository.getById(id);
        if (!cupons) {
            throw new NotFoundError(`Product with id ${id} not found`);
        }
        return this.cuponsRepository.delete(id);
    }
}
module.exports = CuponsService;